name: Trigger Actions in Target Repo
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Actions in Target Repo
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: gucooing/hkrpg-go-public
          event-type: HKRPG-Go-Publish
          client-payload: '{}'
